-- Oracle SQL Schema for Cinema Booking System
-- Run as kumariHall user

-- Drop tables for a clean start (ignore errors if they don't exist)
DROP TABLE TICKET CASCADE CONSTRAINTS;
DROP TABLE SHOWTIMES CASCADE CONSTRAINTS;
DROP TABLE MOVIE CASCADE CONSTRAINTS;
DROP TABLE THEATERCITYHALL CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

-- 1. USERS Table
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    USER_PASSWORD VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    PHONE_NUMBER VARCHAR2(20),
    ADDRESS VARCHAR2(200),
    USER_ROLE VARCHAR2(20) DEFAULT 'Customer' CHECK (USER_ROLE IN ('Admin', 'Customer'))
);

-- 2. THEATERCITYHALL Table
CREATE TABLE THEATERCITYHALL (
    THEATER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    THEATER_NAME VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(200),
    CAPACITY NUMBER NOT NULL
);

-- 3. MOVIE Table
CREATE TABLE MOVIE (
    MOVIE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MOVIE_TITLE VARCHAR2(100) NOT NULL,
    GENRE VARCHAR2(50),
    LANGUAGE VARCHAR2(50),
    DURATION NUMBER -- in minutes
);

-- 4. SHOWTIMES Table
CREATE TABLE SHOWTIMES (
    SHOW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MOVIE_ID NUMBER REFERENCES MOVIE(MOVIE_ID) ON DELETE CASCADE,
    THEATER_ID NUMBER REFERENCES THEATERCITYHALL(THEATER_ID) ON DELETE CASCADE,
    SHOW_TIME TIMESTAMP NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL
);

-- 5. TICKET Table
CREATE TABLE TICKET (
    TICKET_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    SHOW_ID NUMBER REFERENCES SHOWTIMES(SHOW_ID) ON DELETE CASCADE,
    BOOKING_DATE DATE DEFAULT SYSDATE,
    SEAT_NUMBER VARCHAR2(10),
    STATUS VARCHAR2(20) DEFAULT 'Paid'
);

-- Sample Data
-- Sample Data
INSERT INTO USERS (USERNAME, USER_PASSWORD, EMAIL, PHONE_NUMBER, ADDRESS, USER_ROLE) VALUES ('admin', 'admin123', 'admin@cinema.com', '1234567890', 'Main Street', 'Admin');
INSERT INTO USERS (USERNAME, USER_PASSWORD, EMAIL, PHONE_NUMBER, ADDRESS, USER_ROLE) VALUES ('user', 'user123', 'kumar@example.com', '9876543210', 'Kathmandu', 'Customer');
INSERT INTO THEATERCITYHALL (THEATER_NAME, LOCATION, CAPACITY) VALUES ('Kumari Hall 1', 'Kathmandu', 150);
INSERT INTO MOVIE (MOVIE_TITLE, GENRE, LANGUAGE, DURATION) VALUES ('Interstellar', 'Sci-Fi', 'English', 169);

COMMIT;
